In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
moviesDF=pd.read_csv('c:\\IMDB-Movie-Data.csv')
moviesDF.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
4,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0

In [4]:
moviesDF.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [5]:
moviesDF.shape

(1024, 12)

In [7]:
moviesDF.info

<bound method DataFrame.info of       Rank                    Title                     Genre
0        1  Guardians of the Galaxy   Action,Adventure,Sci-Fi  \
1        2               Prometheus  Adventure,Mystery,Sci-Fi
2        3                    Split           Horror,Thriller
3        3                    Split           Horror,Thriller
4        4                     Sing   Animation,Comedy,Family
...    ...                      ...                       ...
1019   996     Secret in Their Eyes       Crime,Drama,Mystery
1020   997          Hostel: Part II                    Horror
1021   998   Step Up 2: The Streets       Drama,Music,Romance
1022   999             Search Party          Adventure,Comedy
1023  1000               Nine Lives     Comedy,Family,Fantasy

                                            Description              Director
0     A group of intergalactic criminals are forced ...            James Gunn  \
1     Following clues to the origin of mankind, a te...          Ridley Scott
2     Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3     Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
4     In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
...                                                 ...                   ...
1019  A tight-knit team of rising investigators, alo...             Billy Ray
1020  Three American college students studying abroa...              Eli Roth
1021  Romantic sparks occur between two dance studen...            Jon M. Chu
1022  A pair of friends embark on a mission to reuni...        Scot Armstrong
1023  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld

                                                 Actors  Year
0     Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014  \
1     Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012
2     James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016
3     James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016
4     Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016
...                                                 ...   ...
1019  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015
1020  Lauren German, Heather Matarazzo, Bijou Philli...  2007
1021  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008
1022  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014
1023  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016

      Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore
0                   121     8.1  757074              333.13       76.0
1                   124     7.0  485820              126.46       65.0
2                   117     7.3  157606              138.12       62.0
3                   117     7.3  157606              138.12       62.0
4                   108     7.2   60545              270.32       59.0
...                 ...     ...     ...                 ...        ...
1019                111     6.2   27585                 NaN       45.0
1020                 94     5.5   73152               17.54       46.0
1021                 98     6.2   70699               58.01       50.0
1022                 93     5.6    4881                 NaN       22.0
1023                 87     5.3   12435               19.64       11.0

[1024 rows x 12 columns]>

In [8]:
moviesDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1024 entries, 0 to 1023
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1024 non-null   int64
 1   Title               1024 non-null   object
 2   Genre               1024 non-null   object
 3   Description         1024 non-null   object
 4   Director            1024 non-null   object
 5   Actors              1024 non-null   object
 6   Year                1024 non-null   int64
 7   Runtime (Minutes)   1024 non-null   int64
 8   Rating              1024 non-null   float64
 9   Votes               1024 non-null   int64
 10  Revenue (Millions)  896 non-null    float64
 11  Metascore           960 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 96.1+ KB

In [9]:
moviesDF.describe()

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1024.000000,1024.000000,1024.000000,1024.000000,1.024000e+03,896.000000,960.000000
mean,490.249023,2012.812500,113.746094,6.741113,1.769684e+05,86.818806,59.141667
std,293.020108,3.202516,19.272648,0.950495,2.018283e+05,110.067305,17.100657
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,232.750000,2010.000000,100.000000,6.200000,3.831625e+04,13.650000,47.000000
50%,488.500000,2014.000000,111.000000,6.800000,1.130870e+05,50.305000,60.000000
75%,744.250000,2016.000000,124.000000,7.400000,2.470792e+05,117.572500,72.000000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

In [10]:
moviesDF.describe(include='all')

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1024.000000,1024,1024,1024,1024,1024,1024.000000,1024.000000,1024.000000,1.024000e+03,896.000000,960.000000
unique,NaN,999,207,1000,644,996,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Ghostbusters,"Action,Adventure,Sci-Fi",Jack Sparrow races to recover the heart of Dav...,Ridley Scott,"Viggo Mortensen, George MacKay, Samantha Isler...",NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,2,54,2,8,2,NaN,NaN,NaN,NaN,NaN,NaN
mean,490.249023,NaN,NaN,NaN,NaN,NaN,2012.812500,113.746094,6.741113,1.769684e+05,86.818806,59.141667
std,293.020108,NaN,NaN,NaN,NaN,NaN,3.202516,19.272648,0.950495,2.018283e+05,110.067305,17.100657
min,1.000000,NaN,NaN,NaN,NaN,NaN,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,232.750000,NaN,NaN,NaN,NaN,NaN,2010.000000,100.000000,6.200000,3.831625e+04,13.650000,47.000000
50%,488.500000,NaN,NaN,NaN,NaN,NaN,2014.000000,111.000000,6.800000,1.130870e+05,50.305000,60.000000
75%,744.250000,NaN,NaN,NaN,NaN,NaN,2016.000000,124.000000,7.400000,2.470792e+05,117.572500,72.000000
max,1000.000000,NaN,NaN,NaN,NaN,NaN,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

In [11]:
moviesDF[['Title','Rank']]

                        Title  Rank
0     Guardians of the Galaxy     1
1                  Prometheus     2
2                       Split     3
3                       Split     3
4                        Sing     4
...                       ...   ...
1019     Secret in Their Eyes   996
1020          Hostel: Part II   997
1021   Step Up 2: The Streets   998
1022             Search Party   999
1023               Nine Lives  1000

[1024 rows x 2 columns]

In [12]:
moviesDF.duplicated()

0       False
1       False
2       False
3        True
4       False
        ...
1019    False
1020    False
1021    False
1022    False
1023    False
Length: 1024, dtype: bool

In [13]:
moviesDF[moviesDF.duplicated()]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
3,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
15,14,Moana,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0
39,31,Why Him?,Comedy,A holiday gathering threatens to go off the ra...,John Hamburg,"Zoey Deutch, James Franco, Tangie Ambrose,Cedr...",2016,111,6.3,48123,60.31,39.0
40,32,Nocturnal Animals,"Drama,Thriller",A wealthy art gallery owner is haunted by her ...,Tom Ford,"Amy Adams, Jake Gyllenhaal, Michael Shannon, A...",2016,116,7.5,126030,10.64,67.0
41,33,X-Men: Apocalypse,"Action,Adventure,Sci-Fi",After the re-emergence of the world's first mu...,Bryan Singer,"James McAvoy, Michael Fassbender, Jennifer Law...",2016,144,7.1,275510,155.33,52.0
42,34,Deadpool,"Action,Adventure,Comedy",A fast-talking mercenary with a morbid sense o...,Tim Miller,"Ryan Reynolds, Morena Baccarin, T.J. Miller, E...",2016,108,8.0,627797,363.02,65.0
43,35,Resident Evil: The Final Chapter,"Action,Horror,Sci-Fi",Alice returns to where the nightmare began: Th...,Paul W.S. Anderson,"Milla Jovovich, Iain Glen, Ali Larter, Shawn R...",2016,107,5.6,46165,26.84,49.0
44,36,Captain America: Civil War,"Action,Adventure,Sci-Fi",Political interference in the Avengers' activi...,Anthony Russo,"Chris Evans, Robert Downey Jr.,Scarlett Johans...",2016,147,7.9,411656,408.08,75.0
45,37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
100,77,The Avengers,"Action,Sci-Fi",Earth's mightiest heroes must come together an...,Joss Whedon,"Robert Downey Jr., Chris Evans, Scarlett Johan...",2012,143,8.1,1045588,623.28,69.0
101,78,Inglourious Basterds,"Adventure,Drama,War","In Nazi-occupied France during World War II, a...",Quentin Tarantino,"Brad Pitt, Diane Kruger, Eli Roth,Mélanie Laurent",2009,153,8.3,959065,120.52,69.0
102,79,Pirates of the Caribbean: Dead Man's Chest,"Action,Adventure,Fantasy",Jack Sparrow races to recover the heart of Dav...,Gore Verbinski,"Johnny Depp, Orlando Bloom, Keira Knightley, J...",2006,151,7.3,552027,423.03,53.0
103,80,Ghostbusters,"Action,Comedy,Fantasy","Following a ghost invasion of Manhattan, paran...",Paul Feig,"Melissa McCarthy, Kristen Wiig, Kate McKinnon,...",2016,116,5.3,147717,128.34,60.0
104,81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
105,82,Captain Fantastic,"Comedy,Drama","In the forests of the Pacific Northwest, a fat...",Matt Ross,"Viggo Mortensen, George MacKay, Samantha Isler...",2016,118,7.9,105081,5.88,72.0
106,83,The Wolf of Wall Street,"Biography,Comedy,Crime","Based on the true story of Jordan Belfort, fro...",Martin Scorsese,"Leonardo DiCaprio, Jonah Hill, Margot Robbie,M...",2013,180,8.2,865134,116.87,75.0
107,84,Gone Girl,"Crime,Drama,Mystery",With his wife's disappearance having become th...,David Fincher,"Ben Affleck, Rosamund Pike, Neil Patrick Harri...",2014,149,8.1,636243,167.74,79.0
108,85,Furious Seven,"Action,Crime,Thriller",Deckard Shaw seeks revenge against Dominic Tor...,James Wan,"Vin Diesel, Paul Walker, Dwayne Johnson, Jason...",2015,137,7.2,301249,350.03,67.0
109,86,Jurassic World,"Action,Adventure,Sci-Fi","A new theme park, built on the original site o...",Colin Trevorrow,"Chris Pratt, Bryce Dallas Howard, Ty Simpkins,...",2015,124,7.0,455169,652.18,59.0
110,87,Live by Night,"Crime,Drama",A group of Boston-bred gangsters set up shop i...,Ben Affleck,"Ben Affleck, Elle Fanning, Brendan Gleeson, Ch...",2016,129,6.4,27869,10.38,49.0
111,88,Avatar,"Action,Adventure,Fantasy",A paraplegic marine dispatched to the moon Pan...,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...",2009,162,7.8,935408,760.51,83.0
112,89,The Hateful Eight,"Crime,Drama,Mystery","In the dead of a Wyoming winter, a bounty hunt...",Quentin Tarantino,"Samuel L. Jackson, Kurt Russell, Jennifer Jaso...",2015,187,7.8,341170,54.12,68.0
113,90,The Accountant,"Action,Crime,Drama",As a math savant uncooks the books for a new c...,Gavin O'Connor,"Ben Affleck, Anna Kendrick, J.K. Simmons, Jon ...",2016,128,7.4,162122,86.20,51.0
114,91,Prisoners,"Crime,Drama,Mystery",When Keller Dover's daughter and her friend go...,Denis Villeneuve,"Hugh Jackman, Jake Gyllenhaal, Viola Davis,Mel...",2013,153,8.1,431185,60.96,74.0

In [16]:
moviesDF.drop_duplicates(inplace=True)
moviesDF.duplicated()

0       False
1       False
2       False
4       False
5       False
        ...
1019    False
1020    False
1021    False
1022    False
1023    False
Length: 1000, dtype: bool

In [20]:
moviesDF.reset_index(drop=True,inplace=True)
moviesDF.index

RangeIndex(start=0, stop=1000, step=1)

In [19]:
moviesDF.isnull()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1019,False,False,False,False,False,False,False,False,False,False,True,False
1020,False,False,False,False,False,False,False,False,False,False,False,False
1021,False,False,False,False,False,False,False,False,False,False,False,False
1022,False,False,False,False,False,False,False,False,False,False,True,False
1023,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
moviesDF.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [25]:
moviesDF.fillna(moviesDF['Revenue (Millions)'].sum(),inplace=True)
moviesDF.isnull().sum()

Rank                  0
Title                 0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
dtype: int64

In [26]:
moviesDF.set_index('Title',inplace=True)

In [27]:
moviesDF

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,72337.96,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,72337.96,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [28]:
l=list()
type(l)

list

In [29]:
moviesDF['Actors']

Title
Guardians of the Galaxy    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
Prometheus                 Noomi Rapace, Logan Marshall-Green, Michael Fa...
Split                      James McAvoy, Anya Taylor-Joy, Haley Lu Richar...
Sing                       Matthew McConaughey,Reese Witherspoon, Seth Ma...
Suicide Squad              Will Smith, Jared Leto, Margot Robbie, Viola D...
                                                 ...
Secret in Their Eyes       Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...
Hostel: Part II            Lauren German, Heather Matarazzo, Bijou Philli...
Step Up 2: The Streets     Robert Hoffman, Briana Evigan, Cassie Ventura,...
Search Party               Adam Pally, T.J. Miller, Thomas Middleditch,Sh...
Nine Lives                 Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...
Name: Actors, Length: 1000, dtype: object

In [30]:
moviesDF['Actors'][0]

'Chris Pratt, Vin Diesel, Bradley Cooper, Zoe Saldana'

In [34]:
type(moviesDF['Actors'][0])

str

In [32]:
moviesDF['Lead Actor']=moviesDF['Actors'].apply(lambda x:x.split(',')[0])

In [33]:
moviesDF.head()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Lead Actor
Title,,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,Chris Pratt
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,Noomi Rapace
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,James McAvoy
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,Matthew McConaughey
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,Will Smith